const VERBS = [
  // A1 — базовые
  ['sein','быть'],['haben','иметь'],['werden','становиться'],['können','мочь'],
  ['müssen','должен'],['sollen','следует'],['wollen','хотеть'],['dürfen','сметь'],
  ['mögen','любить'],['möchten','хотел бы'],['gehen','идти'],['kommen','приходить'],
  ['machen','делать'],['sagen','говорить'],['sehen','видеть'],['sprechen','говорить'],
  ['geben','давать'],['nehmen','брать'],['finden','находить'],['lassen','оставлять'],
  ['stehen','стоять'],['bleiben','оставаться'],['liegen','лежать'],['heißen','называться'],
  ['denken','думать'],['wissen','знать'],['fragen','спрашивать'],['fahren','ехать'],
  ['laufen','бежать'],['arbeiten','работать'],['wohnen','жить'],['kaufen','покупать'],
  ['trinken','пить'],['essen','есть'],['schlafen','спать'],['lesen','читать'],
  ['schreiben','писать'],['hören','слышать'],['spielen','играть'],['lernen','учиться'],
  ['helfen','помогать'],['bringen','приносить'],['öffnen','открывать'],['schließen','закрывать'],
  ['beginnen','начинать'],['enden','заканчивать'],['kennen','знать (лично)'],
  ['verstehen','понимать'],['vergessen','забывать'],['treffen','встречать'],
  ['fliegen','летать'],['schwimmen','плавать'],['singen','петь'],['tanzen','танцевать'],
  ['kochen','готовить'],['waschen','мыть'],['putzen','чистить'],['zeigen','показывать'],
  ['erklären','объяснять'],['warten','ждать'],['zahlen','платить'],['suchen','искать'],
  ['brauchen','нуждаться'],['glauben','верить'],['hoffen','надеяться'],['lieben','любить'],
  ['hassen','ненавидеть'],['kennenlernen','знакомиться'],['vorstellen','представлять'],
  ['herauskommen','выходить'],['ankommen','прибывать'],['abfahren','отъезжать'],
  ['einsteigen','садиться (в транспорт)'],['aussteigen','выходить (из транспорта)'],
  ['umsteigen','пересаживаться'],['landen','приземляться'],['starten','стартовать'],

  // A2
  ['anrufen','звонить'],['aufmachen','открывать'],['aufstehen','вставать'],
  ['ausziehen','выезжать / раздеваться'],['backen','печь'],['bauen','строить'],
  ['besuchen','посещать'],['bezahlen','оплачивать'],['bieten','предлагать'],
  ['bitten','просить'],['buchen','бронировать'],['dauern','длиться'],
  ['einladen','приглашать'],['einschlafen','засыпать'],['einkaufen','делать покупки'],
  ['empfehlen','рекомендовать'],['entscheiden','решать'],['erhalten','получать'],
  ['erkennen','узнавать'],['erlauben','разрешать'],['erreichen','достигать'],
  ['erscheinen','появляться'],['erzählen','рассказывать'],['fallen','падать'],
  ['fangen','ловить'],['fehlen','недоставать'],['fernsehen','смотреть ТВ'],
  ['folgen','следовать'],['freuen','радоваться'],['frühstücken','завтракать'],
  ['führen','вести'],['gelingen','удаваться'],['genießen','наслаждаться'],
  ['gewinnen','выигрывать'],['grüßen','приветствовать'],['halten','держать'],
  ['hängen','висеть'],['holen','брать / забирать'],['interessieren','интересовать'],
  ['klingen','звучать'],['kosten','стоить'],['legen','класть'],['leiden','страдать'],
  ['melden','сообщать'],['merken','замечать'],['mieten','арендовать'],
  ['mitbringen','приносить с собой'],['mitnehmen','брать с собой'],
  ['nennen','называть'],['nutzen','использовать'],['packen','паковать'],
  ['passen','подходить'],['planen','планировать'],['prüfen','проверять'],
  ['rechnen','считать'],['reden','говорить'],['reisen','путешествовать'],
  ['rennen','бежать'],['rufen','звать'],['schicken','посылать'],
  ['schneiden','резать'],['setzen','сажать'],['sitzen','сидеть'],
  ['sorgen','заботиться'],['sparen','экономить'],['spazieren','гулять'],
  ['stellen','ставить'],['sterben','умирать'],['stoppen','останавливать'],
  ['studieren','учиться в вузе'],['tragen','носить'],['trainieren','тренироваться'],
  ['träumen','мечтать'],['treten','ступать'],['übernachten','ночевать'],
  ['umziehen','переезжать'],['unterrichten','обучать'],['verabschieden','прощаться'],
  ['verbinden','соединять'],['verbringen','проводить время'],['verdienen','зарабатывать'],
  ['verkaufen','продавать'],['verlassen','покидать'],['verlieren','терять'],
  ['verreisen','уезжать'],['versuchen','пытаться'],['vorbereiten','готовить'],
  ['wechseln','менять'],['weinen','плакать'],['wiederholen','повторять'],
  ['wünschen','желать'],['zeichnen','рисовать'],['zuhören','слушать'],
  ['zumachen','закрывать'],['zurückkommen','возвращаться'],['absagen','отменять'],
  ['abschließen','завершать'],['anbieten','предлагать'],['anfangen','начинать'],
  ['anmachen','включать'],['anprobieren','примерять'],['anschauen','смотреть'],
  ['antworten','отвечать'],['aufhören','прекращать'],['aufnehmen','записывать'],
  ['aufräumen','убирать'],['ausgehen','выходить'],['ausmachen','выключать'],
  ['ausruhen','отдыхать'],['aussehen','выглядеть'],['beachten','соблюдать'],
  ['bedanken','благодарить'],['bedeuten','означать'],['beenden','заканчивать'],
  ['begleiten','сопровождать'],['bekommen','получать'],['benutzen','использовать'],
  ['bestellen','заказывать'],['bewegen','двигать'],['einziehen','въезжать'],
  ['herausfinden','выяснять'],['herstellen','производить'],['hinzufügen','добавлять'],
  ['nachdenken','раздумывать'],['telefonieren','звонить по телефону'],
  ['überweisen','переводить деньги'],['verbessern','улучшать'],
  ['vereinbaren','договариваться'],['vergleichen','сравнивать'],
  ['verwalten','управлять'],['vorschlagen','предлагать'],['zählen','считать'],
  ['zustimmen','соглашаться'],['abholen','забирать'],['abbiegen','поворачивать'],

  // B1
  ['anerkennen','признавать'],['anpassen','адаптировать'],['ansehen','смотреть'],
  ['anstreben','стремиться'],['anwenden','применять'],['aufbauen','строить'],
  ['auffordern','призывать'],['aufgeben','сдаваться / сдавать'],['aufhalten','задерживать'],
  ['aufklären','разъяснять'],['auflösen','растворять'],['aufmerksam machen','обращать внимание'],
  ['aufzeigen','показывать'],['ausbilden','обучать'],['ausdrücken','выражать'],
  ['ausführen','выполнять'],['ausgeben','тратить'],['aushalten','выдерживать'],
  ['ausleihen','одалживать'],['ausmachen','составлять'],['ausnehmen','исключать'],
  ['ausrichten','выравнивать'],['aussagen','заявлять'],['auswählen','выбирать'],
  ['beantragen','подавать заявку'],['bearbeiten','обрабатывать'],['bedenken','учитывать'],
  ['bedienen','обслуживать'],['beeinflussen','влиять'],['befinden','находиться'],
  ['behalten','сохранять'],['beherrschen','владеть'],['beinhalten','содержать'],
  ['bemühen','стараться'],['benötigen','нуждаться'],['beraten','консультировать'],
  ['beschreiben','описывать'],['besitzen','владеть'],['bestehen','состоять / выдержать'],
  ['bestimmen','определять'],['betonen','подчёркивать'],['betrachten','рассматривать'],
  ['bewerten','оценивать'],['bezeichnen','обозначать'],['bitten','просить'],
  ['darstellen','представлять'],['durchführen','проводить'],['eingehen','входить'],
  ['einhalten','соблюдать'],['einrichten','устраивать'],['einstellen','нанимать'],
  ['enthalten','содержать'],['entschuldigen','извинять'],['entsprechen','соответствовать'],
  ['entwickeln','развивать'],['erarbeiten','разрабатывать'],['erfassen','охватывать'],
  ['erfüllen','выполнять'],['ergänzen','дополнять'],['erledigen','выполнять'],
  ['ermöglichen','делать возможным'],['erwarten','ожидать'],['erzeugen','производить'],
  ['feststellen','устанавливать'],['fördern','поддерживать'],['fortsetzen','продолжать'],
  ['gestalten','оформлять'],['gestatten','позволять'],['gewähren','предоставлять'],
  ['handeln','действовать'],['hervorheben','выделять'],['hinweisen','указывать'],
  ['informieren','информировать'],['kombinieren','комбинировать'],['kontrollieren','контролировать'],
  ['koordinieren','координировать'],['lösen','решать'],['mitteilen','сообщать'],
  ['organisieren','организовывать'],['präsentieren','презентовать'],['reagieren','реагировать'],
  ['realisieren','реализовывать'],['stattfinden','происходить'],['übernehmen','перенимать'],
  ['übertragen','передавать'],['umsetzen','реализовывать'],['unterstützen','поддерживать'],
  ['verantworten','отвечать за'],['verbreiten','распространять'],['verfügen','располагать'],
  ['verhindern','предотвращать'],['vermeiden','избегать'],['versichern','страховать'],
  ['verteilen','распределять'],['verwenden','использовать'],['voraussetzen','предполагать'],
  ['vorgehen','действовать'],['vorlegen','представлять'],['wahrnehmen','воспринимать'],
  ['weitergehen','продолжать идти'],['wenden','обращаться'],['zuordnen','распределять'],

  // B2
  ['absichern','обеспечивать'],['abstimmen','согласовывать'],['analysieren','анализировать'],
  ['anfordern','запрашивать'],['aufweisen','обнаруживать'],['auseinandersetzen','разбираться'],
  ['auswerten','оценивать'],['begründen','обосновывать'],['beurteilen','оценивать'],
  ['bewältigen','справляться'],['einschätzen','оценивать'],['erforschen','исследовать'],
  ['erörtern','обсуждать'],['festlegen','устанавливать'],['formulieren','формулировать'],
  ['garantieren','гарантировать'],['gegenüberstellen','сопоставлять'],
  ['hervorbringen','производить'],['interpretieren','интерпретировать'],
  ['nachweisen','доказывать'],['optimieren','оптимизировать'],['rechtfertigen','оправдывать'],
  ['schlußfolgern','делать вывод'],['strukturieren','структурировать'],
  ['überarbeiten','перерабатывать'],['überwinden','преодолевать'],['untersuchen','исследовать'],
  ['veranlassen','организовывать'],['veröffentlichen','публиковать'],['vervollständigen','завершать'],
  ['widersprechen','противоречить'],['zusammenfassen','подводить итог'],
  ['zusammenhängen','быть связанным'],

  // Повседневные / полезные
  ['abnehmen','худеть / снимать'],['abonnieren','подписываться'],['abspielen','воспроизводить'],
  ['anklicken','нажимать'],['anmelden','регистрироваться'],['annehmen','принимать'],
  ['aufwachen','просыпаться'],['ausdrucken','распечатывать'],['ausloggen','выходить из системы'],
  ['basteln','мастерить'],['bedienen','обслуживать'],['beibringen','обучать'],
  ['beitragen','вносить вклад'],['beschäftigen','занимать'],['bezweifeln','сомневаться'],
  ['duschen','принимать душ'],['einloggen','входить в систему'],['einstecken','вставлять'],
  ['empfangen','принимать'],['entspannen','расслабляться'],['fotografieren','фотографировать'],
  ['fressen','жрать (о животных)'],['genügen','хватать'],['herunterladen','скачивать'],
  ['hochladen','загружать'],['installieren','устанавливать'],['joggen','бегать'],
  ['kämmen','расчёсывать'],['klingeln','звонить (в дверь)'],['klopfen','стучать'],
  ['lächeln','улыбаться'],['lachen','смеяться'],['malen','рисовать'],
  ['meinen','считать'],['mieten','снимать жильё'],['nachschlagen','смотреть в словаре'],
  ['nicken','кивать'],['niesen','чихать'],['rasieren','бриться'],['rauchen','курить'],
  ['reservieren','резервировать'],['schminken','краситься'],['schnäuzen','сморкаться'],
  ['schwitzen','потеть'],['spülen','полоскать'],['streicheln','гладить'],
  ['stricken','вязать'],['surfen','сёрфить'],['tippen','печатать'],
  ['trösten','утешать'],['umarmen','обнимать'],['verbinden','соединять'],
  ['vergeben','прощать'],['versprechen','обещать'],['vertrauen','доверять'],
  ['weiterleiten','переадресовывать'],['wischen','вытирать'],['zanken','ссориться'],
  ['zögern','медлить'],['zuhören','слушать внимательно'],
  ['scheiben','катить, двигать вперед'],
];
